Added notes on gov cloud uri and graph endpoint
Azure-Samples/active-directory-dotnet-desktop-msgraph-v2 pull request #44
Opened 2020-02-07 22:42 UTC by aiwangmicrosoft

2020-02-08 19:40 UTC, jmprieur requested changes
Good start @aiwangmicrosoft 
proposed a few improvements

2020-02-08 19:40 UTC, jmprieur commented on README.md
> +1. If connecting to a national cloud, open the 'active-directory-wpf-msgraph-v2\MainWindow.xaml.cs' file and update string graphAPIEndpoint to the appropriate endpoint.
- please use the back quote sign around `graphAPIEndpoint` to higlight it.
- please provide a link to the endpoints

2020-02-10 18:11 UTC, aiwangmicrosoft commented
Fixed the comments, @jmprieur can you review?

2020-02-10 18:52 UTC, jmprieur approved these changes
LGTM. Thanks @aiwangmicrosoft

2020-02-10 18:52 UTC, merged